spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: "jdbc:mysql://localhost:3306/cooking_recipes?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
        username: root
        password: 1205
    servlet:
        multipart:
            max-file-size: 1MB
            max-request-size: 5MB
    mvc:
        hiddenmethod:
            filter:
                enabled: true
    sql:
        init:
#           mode: always
            mode: never
#           should be always on first start

    jpa:
        # Choose either MySQL 8 or MySQL 5 below
        # For MySQL 8
        database-platform: org.hibernate.dialect.MySQL8Dialect
        #For MySQL 5
        #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        #database-platform: org.hibernate.dialect. something MariaDB
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
        defer-datasource-initialization: true
    #Cloudinary Properties cloud
    #cloudinary:
    #api-key:
    #api-secret:
    #cloud-name:
server:
    port: 8000

#logging:
#    level:
#        blog: WARN
#        org: WARN
#        org.hibernate.SQL: DEBUG
#server:
#    port: 8000
#spring:
#    datasource:
#        driverClassName: com.mysql.cj.jdbc.Driver
#        password: 1205
#        url: jdbc:mysql://localhost:3306/cooking_recipes10?createDatabaseIfNotExist=true
#        username: root
#sql:
#    init:
#       mode: always
#     #   mode: never
#        # should be always on first start
#
#    jpa:
#        hibernate:
#            ddl-auto: update
##        ddl-auto: create-drop
#        open-in-view: false
#        properties:
#            hibernate:
#                dialect: org.hibernate.dialect.MySQL8Dialect
#                format_sql: true
